version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
      - db:mysql
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      DB_HOST: mysqlhost
    ports:
      - "3306:3306"        